# This is the docker-compose-yml file that must be able to start
# your group's backend.

# Remember to comment this file well!

# After you have Docker and Docker Compose installed,
# and this file is ready, you use this file and run it with:
# `docker-compose up --build`

version: "3"

services:

  orig:
    depends_on:
      -  rapid-runner-rabbit
      -  obse
      -  orig
    command: ["node", "main.js"]
    build:
      dockerfile: Dockerfile
      context:  ./ORIG
    networks:
      - lassenet

  obse:
    depends_on:
      -  rapid-runner-rabbit
    command: ["node", "obse.js"]
    build:
      dockerfile: Dockerfile
      context:  ./ORIG
    networks:
      - lassenet

  httpserv:
    # Change the image information to match your server A image
    # image: # $USERNAME/$IMAGENAME:$TAG, something like group000/node-swagger:3a
    # 'depends_on' and 'command' are  to be used when used
    # with RabbitMQ service in this file. 'depends_on' must be set
    # to RabbitMQ service's name from this file, and 'command'
    # can be modified to be anything, but what is given should
    # work. Just uncomment them
    depends_on:
      -  rapid-runner-rabbit
    command: ["node", "index.js"]
    build:
      dockerfile: Dockerfile
      context:  ./HTTPSERV
    # Here we map the port 8080 of the container to the
    # port 3000 of the host. Container port has been exposed
    # in the node:10 Docker Hub Dockerfile.
    ports:
      - "3000:8080"
    networks:
      - lassenet


  rapid-runner-rabbit:
    image: rabbitmq:3-management
    expose:
      - "5672"
    networks:
      - lassenet

  # much of the server-b service entry can be copied from server-a
  # service above. server-b directory Dockerfile has more
  # information.
  # A set of needed Docker instructions like 'image:' are shown
  # below, groups should set their values. Groups are free to
  # CRUD this set of instructions as they see fit.
  imed:
    depends_on:
      -  rapid-runner-rabbit
    command: ["node", "index.js"]
    build:
      dockerfile: Dockerfile
      context:  ./IMED
    networks:
      - lassenet

networks:
  lassenet:

