

version: "3"

services:
  orig:
    depends_on:
      -  rapid-runner-rabbit
      -  obse
      -  imed
    command: ["node", "main.js"]
    build:
      dockerfile: Dockerfile
      context:  ./ORIG
    networks:
      - lassenet

  obse:
    depends_on:
      -  rapid-runner-rabbit
    command: ["node", "obse.js"]
    build:
      dockerfile: Dockerfile
      context:  ./ORIG
    networks:
      - lassenet

  httpserv:

    depends_on:
      -  rapid-runner-rabbit
    command: ["node", "index.js"]
    build:
      dockerfile: Dockerfile
      context:  ./HTTPSERV

    ports:
      - "8080:8894"

    networks:
      - lassenet


  rapid-runner-rabbit:
    image: rabbitmq:3-management
    expose:
      - "5672"
    networks:
      - lassenet


  imed:
    depends_on:
      -  rapid-runner-rabbit
    command: ["node", "index.js"]
    build:
      dockerfile: Dockerfile
      context:  ./IMED
    networks:
      - lassenet

networks:
  lassenet:

